apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: gitea-ingress
  labels:
    app: gitea
spec:
  rules:
  - host: gitea.playwithdocker.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: gitea
          servicePort: 3000
