apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-ingress
spec:
 rules:
  - host: nginx.playwithdocker.ml
    http:
      paths:
         - path: /v2
           backend:
              serviceName: "service-2048"
              servicePort: 80
