apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-ingress
    annotations:
      kubernetes.io/ingress.class: alb
spec:
 rules:
  - host: mynginx.com
    http:
      paths:
         - path: /*
           backend:
              serviceName: "nginx-hpa-service"
              servicePort: 80
