apiVersion: v1
kind: Pod
metadata:
   name: secret-pod-1
spec:
  containers:
      - name: secret-container
        image: nginx
        env:
        - name: USERNAME
          valueFrom:
               secretKeyRef:
                    name: my-pass
                    key: username
