apiVersion: v1
kind: Pod
metadata:
   name: secret-pod
spec:
  containers:
      - name: secret-container
        image: nginx
        volumeMounts:
             - name: pod-vol
               mountPath: /opt/secret
  volumes:
     - name: pod-vol
       secret:
           secretName: my-pass
