apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    command:
      - env
    env:
    - name: username
      valueFrom:
           secretKeyRef:
                name: db-cred
                key: username
    - name: passwd
      valueFrom:
           secretKeyRef:
               name: db-cred
               key: passwd
