apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "Chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.imageName }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
               - name: application-config
                 mountPath: /usr/share/nginx/html/ 
          readinessProbe:
{{- if .Values.deployment.readinessProbe }}
{{ toYaml .Values.deployments.readinessProbe | indent 12  }}
{{- else }}
            httpGet:
             path: {{ .Values.deployment.readiness.httpGet.path }}
             port: {{ .Values.deployment.readiness.httpGet.port }}
            initialDelaySeconds: {{ .Values.deployment.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readiness.periodSeconds }}
            successThreshold: {{ .Values.deployment.readiness.successThreshold }}
            failureThreshold: {{ .Values.deployment.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.deployment.readiness.timeoutSeconds }}
{{- end }}
          volumes:
              - name: application-config
                configMap:
                    name: {{ .Chart.name }}-config
                    items:
                    - key: "index.html"
                      path: "index.html" 
