apiVersion: v1
kind: Pod
metadata:
     name: nginx
spec:
  containers:
     - name: nginx-container
       image: nginx
       volumeMounts:
           - name: first-config 
             mountPath: /configmap
  volumes:
    - name: first-config
      configMap:
          name: myconfig
          items:
           - key: configdata.properties 
             path: config.conf
