version: '3'
services:
    mongo:
      image: mongo:latest
      container_name: mongo
      volumes:
        - mongodb:/data/db
      ports:
       - 27017:27017
      healthcheck:
          test: ["CMD-SHELL" , "mongo || exit 1"]
          interval: 30s
          timeout: 10s
          retries: 2
          start_period: 10s

    knote-app:
        depends_on:
          - mongo
        build: .
        container_name: knote-app
        environment:
             MONGO_URL: mongodb://mongo:27017/dev
        ports:
          - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 10s
        links:
          - mongo
volumes:
    mongodb:
