apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-persistent-storage
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: "gitea"