apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:latest
          volumeMounts:
            - name: gitea-volume
              mountPath: "/data"
      volumes:
         - name: gitea-volume
           persistentVolumeClaim:
              claimName: gitea-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: gitea-persistent-storage
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: managed-nfs-storage
   resources:
      requests:
          storage: 1Gi
