apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  ports:
  - port: 80
  type: NodePort
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
