kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stash-storage
  labels:
    app: bitbucket
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
