apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginxv1
  template:
    metadata:
        labels:
            app: nginxv1
    spec:
        containers:
            - name: first-container
              image: mak1806/k8s-nginx:1
              command: ["/home/auto-reload-nginx.sh"]
              ports:
               - containerPort: 443
               - containerPort: 80
              volumeMounts:
              - mountPath: /etc/nginx/ssl
                name: ssl-cert
              - mountPath: /etc/nginx/conf.d
                name: nginx-files
        
        volumes:
        - name: ssl-cert
          secret:
             secretName: nginxsecret
        - name: nginx-files
          configMap:
            name: nginxconfigmap
