apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginxv1
  template:
    metadata:
        labels:
            app: nginxv1
    spec:
        initContainers:
          - name: ssl-cert-creation
            image: frapsoft/openssl
            command: ["/bin/sh"]
            args: ["-c","mkdir -p /etc/nginx/ssl;openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/nginx.key -x509 -days 365 -out /etc/nginx/ssl/nginx.crt -subj '/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com'"]
            volumeMounts: 
            - name: ssl-cert
              mountPath: /etc/nginx/ssl
       
        containers:
            - name: first-container
              image: mak1806/k8s-nginx:1
              command: ["/home/auto-reload-nginx.sh"]
              ports:
               - containerPort: 443
               - containerPort: 80
              volumeMounts:
              - mountPath: /etc/nginx/ssl
                name: ssl-cert
              - mountPath: /etc/nginx/conf.d
                name: nginx-files
        
        volumes:
        - name: ssl-cert
          emptyDir: {}
        - name: nginx-files
          configMap:
            name: nginx-config
            
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginxv1
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginxv1
