apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginxv1
  template:
    metadata:
        labels:
            app: nginxv1
    spec:
        initContainers:
          - name: ssl-cert-creation
            image: frapsoft/openssl
            command: ["/bin/sh"]
            args: ["-c","mkdir -p /etc/nginx/ssl;openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/nginx.key -x509 -days 365 -out /etc/nginx/ssl/nginx.crt -subj '/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com'"]
            volumeMounts: 
            - name: ssl-cert
              mountPath: /etc/nginx/ssl
       
        containers:
            - name: first-container
              image: mak1806/k8s-nginx:1
              command: ["/home/auto-reload-nginx.sh"]
              ports:
               - containerPort: 443
               - containerPort: 80
              resources:
                 limits:
                   cpu: "100m"
                   memory: "500Mi"
                 requests:
                   cpu: "200m"
                   memory: "1Gi"
              readinessProbe:
                httpGet:
                  path: /
                  port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
                timeoutSeconds: 1
     
              volumeMounts:
              - mountPath: /etc/nginx/ssl
                name: ssl-cert
              - mountPath: /etc/nginx/conf.d
                name: nginx-files
        
        volumes:
        - name: ssl-cert
          emptyDir: {}
        - name: nginx-files
          configMap:
            name: nginx-config
            
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       simple-deployment
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginxv1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32324
    protocol: TCP
    name: http
  - port: 443
    nodePort: 32325
    protocol: TCP
    name: https
  selector:
    app: nginxv1
