# Create PersistentVolume for gitea server
# change the ip of NFS server

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-persistent-storage
  labels:
    app: gitea
spec:
  capacity:
    storage: 1Gi
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  nfs:
    server: 3.#####.90  # Exported path of your NFS server
    path: "/gitea"
