apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: test
    namespace: default
subjects:
    - kind: ServiceAccount
      name: test
      apiGroup: ""
      namespace: default
roleRef:
    kind: ClusterRole
    name: test
    apiGroup: ""

