######################### exmaple of node selector ########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
     rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
     type: RollingUpdate
  selector:
    matchLabels:
       app: nginx-app
  template:
    metadata:
      labels:
       app: nginx-app
    spec:
     serviceAccountName: test
     initContainers:
         - name: shell-code
           image: "deekshithsn/jq:1.0"
           command: ["/bin/sh"]
           args: ["-c", "sh /tmp/api.sh"]
           volumeMounts:
                - name: shell
                  mountPath: /tmp/
                - name: html
                  mountPath: /code/
     containers:
       - name: nginx-containers
         image: nginx
         volumeMounts:
              - name: html
                mountPath: /usr/share/nginx/html
         ports:
          - containerPort: 80
          - containerPort: 443
     volumes:
        - name: shell
          configMap:
              name: shell-code
        - name: html
          emptyDir: {}
