apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 3.20.66.155
    path: "/nfs-private/pv0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 3.20.66.155
    path: "/nfs-private/pv1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 3.20.66.155
    path: "/nfs-private/pv2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 3.20.66.155
    path: "/nfs-private/pv3"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 3.20.66.155
    path: "/nfs-private/pv4"
