apiVersion: v1
kind: Service
metadata:
   name: nginx-service
   labels:
      app: nginx-app
spec:
  selector:
       statefulset.kubernetes.io/pod-name: nginx-sts-0
       statefulset.kubernetes.io/pod-name: nginx-sts-1
       statefulset.kubernetes.io/pod-name: nginx-sts-2
       statefulset.kubernetes.io/pod-name: nginx-sts-3
       statefulset.kubernetes.io/pod-name: nginx-sts-4
  type: NodePort
  ports:
   - port: 80
