apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint-toleration
spec:
  containers:
  - image: nginx
    name: nginx
  tolerations:
      - key: "taint_key"
        operator: "Equal"
        value: "taint_value"
        effect: "NoSchedule"
