apiVersion: v1
kind: Pod
metadata:
  name: nginx-taint-toleration-2
spec:
  containers:
  - image: nginx
    name: nginx
  tolerations:
      - key: "taint_key"
        operator: "Exists"
        effect: "NoSchedule"
