apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "my.name" . }}-config
    labels:
       tag: {{ .Values.image.tag }}
       env: {{ .Values.env }}
    annotations:
       "helm.sh/hook": pre-install
data:
   index.html: |
{{ .Files.Get (printf "env/application-%s.html" .Values.env)  | indent 6 }}
