# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
     version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
            app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: mak1806/myapp:v2
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
            requests:
                cpu: 70m
                memory: 30Mi
