replicasCount: 2

env: dev

image:
   pullPolicy: IfNotPresent
   imageName: nginx
   tag: latest

service:
   type: NodePort
   port: 8080
   nodePort: 32323
 
deployment:
 readiness:
  httpGet:
   path: /
   port: http
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 10
