env: dev
appname: nginxtest

image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "1.21.4"

deployment:
 enabled: true

 replicas: 2

 rollingStrategy:
    maxUnavailable: 50%

 memory:
   request: 1024Mi
   limit: 1024Mi

 workingDir: "/usr/share/nginx/html/"

 readiness:
  httpGet:
   path: /
   port: 80
  initialDelaySeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 20

 liveness:
  httpGet:
   path: /
   port: 80
  initialDelaySeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 20

service:
   enabled: true
   type: NodePort
   port: 80
   nodePort: 32323
