apiVersion: apps/v1
kind: Deployment
metadata:
    name: simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginxv1
  template:
    metadata:
        labels:
            app: nginxv1
    spec:
        containers:
            - name: first container
              image: nginx
              ports:
               - containerPort: 80
