apiVersion: apps/v1
kind: Deployment
metadata:
   name: demo
   namespace: default
   labels:
     app: nginxv1
spec:
  replicas: 1
  selector:
      matchLabels:
          app: nginxv1
  strategy:
      rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      type: RollingUpdate
  template:
      metadata:
         labels:
           app: nginxv1
      spec:
       containers:
           - name: demo
             image: nginx
             volumeMounts:
                  - name: foo
                    mountPath: /opt
             env:
              - name: name
                valueFrom:
                    secretKeyRef:
                         name: adil
                         key: name
             ports:
              - containerPort: 80
             resources:
                limits:
                  memory: 100Mi
                requests:
                  memory: 100Mi
             readinessProbe:
                 httpGet:
	            path: /
                    port: 80
                 initialDelaySeconds: 5
                 periodSeconds: 2
       volumes:
          - name: foo
            secret:
               secretName: demo
