apiVersion: v1
kind: Pod
metadata:
   name: test-vol
spec:
  containers:
   - image: nginx
     name: test-container
     volumeMounts:
       - mountPath: /home/ubuntu/ 
         name: test-vol
  volumes:
  - name: test-vol
    hostPath:
          path: /home/ubuntu/
