apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-for-pod
  labels:
    name: pvc-busy-box
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
   name: test-vol
spec:
  containers:
   - image: busybox
     name: test-container
     volumeMounts:
       - name: nfs-dynamic-storage
         mountPath: /nfs-storage-on-pod
  volumes:
  - name: nfs-dynamic-storage
  persistentVolumeClaim:
  claimName: pvc-for-pod
