apiVersion: v1
kind: Pod
metadata:
   name: test-vol
spec:
  containers:
   - image: nginx
     name: test-container
     volumeMounts:
       - name: test-vol
         mountPath: /cache
  volumes:
  - name: test-vol
    emptyDir: {}
