


apiVersion: v1
kind: Pod
metadata:
   name: project-1
   labels:
     app: nginx-app
spec:
  containers:
    - name: container01
      image: nginx:latest
      volumeMounts:
         - name: my-vol
           mountPath: /usr/share/nginx/html
      ports:
        -  containerPort: 80
  volumes:
   - name: my-vol
     hostPath:
             path: /usr/share/nginx/html
