


apiVersion: v1
kind: Pod
metadata:
   name: project-1
   labels:
     app: nginx
spec:
  containers:
    - name: container01
      image: nginx:latest
      volumeMounts:
         - name: my-vol
           mountPath: /usr/share/nginx/html

    - name: container02
      image: alpine
      volumeMounts:
       - name: my-vol
         mountPath: /my-vol
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
           date >> /html/index.html;
           sleep 1;
          done
       
  volumes:
    -name: my-vol
     emptyDir: {}