apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-vol
   labels:
       type: local
spec:
   accessModes:  
      - ReadWriteOnce
   storageClassName: manual
   capacity:
       storage: 50Mi
   hostPath:
       path: "/mnt/data"
