---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
  annotations:
    fluxcd.io/tag.nginx-containers: semver:~1.0
    fluxcd.io/automated: "true"
    fluxcd.io/locked_msg: 1.0.2 not works
    fluxcd.io/locked_user: Khan adil <khanabdullahadil@gmail.com>
    fluxcd.io/locked: 'true'
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 3
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-containers
        image: mak1806/custom-nginx:1.0.3
        ports:
        - containerPort: 80
