apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  replicas: 5
  minReadySeconds: 5
  strategy:
     rollingUpdate:
          maxSurge: 0
          maxUnavailable: 3
     type: RollingUpdate
  selector:
    matchLabels:
       app: nginx-app
  template:
    metadata:
      labels:
       app: nginx-app
    spec:
     containers:
       - name: nginx-containers
         image: mak1806/custom-nginx:v1.0
         ports:
          - containerPort: 80
