kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
subjects:
# Kubernetes service account
- kind: ServiceAccount
  name: pod-reader-sa 
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
