apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
      path: "/opt/sql"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nginx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
      path: "/opt/sql"
