apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
